name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # conda/conda-forge packages
  - gdal[numpy]
  - pip
  # pip/PyPI packages
  - pip:
      - rana-process-sdk==0.3
      - threedi_schema
      - GeoAlchemy2
